const quizData = {
    "9e AF": [
        { subject: "Français", question: "Qui a écrit 'Gouverneurs de la Rosée' ?", answers: ["Jacques Roumain", "Frankétienne", "Dany Laferrière"], correct: 0 },
        { subject: "Maths", question: "Quelle est la racine carrée de 81 ?", answers: ["8", "9", "10"], correct: 1 },
        { subject: "Sciences Sociales", question: "En quelle année Haïti a-t-elle proclamé son indépendance ?", answers: ["1791", "1801", "1804"], correct: 2, explanation: "L'indépendance d'Haïti a été proclamée le 1er janvier 1804 par Jean-Jacques Dessalines, faisant d'Haïti la première république noire libre du monde." },
        { subject: "Physique", question: "Quelle unité mesure la force ?", answers: ["Le Watt", "Le Newton", "Le Joule"], correct: 1 },
        { subject: "Anglais", question: "How do you say 'bonjour' in English?", answers: ["Good evening", "Hello", "Goodbye"], correct: 1 },
        { subject: "Créole", question: "Kisa 'lakay' vle di an franse ?", answers: ["Maison", "Marché", "École"], correct: 0 },
        { subject: "Espagnol", question: "¿Cómo se dice 'rojo' en francés?", answers: ["Bleu", "Vert", "Rouge"], correct: 2 },
        { subject: "EPS", question: "Combien de joueurs composent une équipe de football sur le terrain ?", answers: ["9", "11", "13"], correct: 1 },
        { subject: "ETAP", question: "Quel outil est utilisé pour planter un clou ?", answers: ["Une scie", "Un marteau", "Un tournevis"], correct: 1 },
        { subject: "EC", question: "Quel est le symbole de la justice ?", answers: ["Une colombe", "Une balance", "Un lion"], correct: 1 },
        { subject: "EEA", question: "Quelle couleur obtient-on en mélangeant du bleu et du jaune ?", answers: ["Le rouge", "Le violet", "Le vert"], correct: 2 }
    ],
    SES: [
        { subject: "Économie", question: "Qu'est-ce que le PIB ?", answers: ["Produit Intérieur Brut", "Parti Intérieur Basque", "Produit Industriel de Base"], correct: 0 },
        { subject: "Sciences Sociales", question: "Qui est considéré comme le père de la sociologie moderne ?", answers: ["Karl Marx", "Émile Durkheim", "Max Weber"], correct: 1 },
        { subject: "Philosophie", question: "Que signifie 'Cogito, ergo sum' ?", answers: ["Je pense, donc je suis", "Je vois, donc je crois", "J'agis, donc j'existe"], correct: 0 },
        { subject: "Histoire", question: "En quelle année a eu lieu la Révolution française ?", answers: ["1789", "1848", "1917"], correct: 0 },
        { subject: "Maths", question: "Si un article coûte 100 gourdes et est soldé à 20%, quel est son nouveau prix ?", answers: ["80 gourdes", "120 gourdes", "20 gourdes"], correct: 0 }
    ],
    SVT: [
        { subject: "Biologie", question: " Quelle est la cause du syndrome de Down ?", answers: ["Une mutation génétique sur un seul gène", "Une trisomie du chromosome 21", "Une infection pendant la grossesse","Une carence en vitamines"], correct: 2 , explanation:" Le syndrome de Down est causé par la présence d’un chromosome 21 supplémentaire (trisomie 21)." },
        { subject: "Biologie", question: " Les individus atteints du syndrome de Down présentent souvent un retard mental et des traits physiques caractéristiques.", answers: ["Vrai", "Faux", "Les Deux"], correct: 1 , explanation:" Les traits incluent un visage plat, des yeux en amande et une déficience intellectuelle variable." },
        { subject: "Biologie", question: " Que représente un caryotype ?", answers: ["L’ensemble des chromosomes d’une cellule organisés par paire ", "Une séquence d’ADN", "Une cellule spécialisée", " Un type de cellule sanguine"], correct: 1 , explanation:" Un caryotype est l’image ordonnée des chromosomes d’une cellule, classés par taille et forme." },
        { subject: "Biologie", question: " Quelle est la différence entre autosomes et hétérochromosomes ?", answers: ["Les autosomes déterminent le sexe ; les hétérochromosomes non", "Les autosomes ne déterminent pas le sexe ; les hétérochromosomes déterminent le sexe", " Les autosomes sont seulement chez les femelles", "Les hétérochromosomes sont présents dans toutes les cellules identiques"], correct: 2 , explanation:"Les 22 premières paires sont des autosomes (non sexuels), la 23ᵉ paire (X et Y) détermine le sexe."},
        { subject: "Biologie", question: " Que sécrètent les acini pancréatiques ?", answers: ["Insuline", "Glucagon", "Enzymes digestives", "Adrénaline"], correct: 3 , explanation:" Les acini pancréatiques produisent des enzymes digestives comme l’amylase et la lipase." },
        { subject: "Biologie", question: " Quelle est la différence entre les cellules alpha et bêta des îlots de Langerhans ?", answers: [" Alpha → insuline ; Bêta → glucagon", "Alpha → glucagon ; Bêta → insuline", "Alpha → enzymes digestives ; Bêta → glucagon","Alpha → adrénaline ; Bêta → insuline"], correct: 2 , explanation:"Les cellules alpha produisent le glucagon, les cellules bêta produisent l’insuline, régulant la glycémie." },
        { subject: "Biologie", question: " Un diabétique de type I est insulinodépendant car son pancréas ne produit pas d’insuline.", answers: ["Vrai", "Faux"], correct: 1 , explanation:"Les cellules bêta étant détruites, le patient doit recevoir de l’insuline extérieurement." },
        { subject: "Biologie", question: " Quelle est la différence entre rachitisme et ostéomalacie ?", answers: ["Rachitisme → adultes ; Ostéomalacie → enfants", "Rachitisme → enfants ; Ostéomalacie → adultes", "Rachitisme → manque de protéines ; Ostéomalacie → manque de calcium","Pas de différence"], correct: 2 , explanation:"  Le rachitisme touche les enfants avec mauvaise ossification ; l’ostéomalacie touche les adultes avec ramollissement des os." },
        { subject: "Biologie", question: " Pourquoi un individu de groupe sanguin AB est-il receveur universel ?", answers: [" Il peut donner son sang à tous", "Il ne peut recevoir que du sang AB", " Il a des anticorps pour tous les groupes","Il possède à la surface des globules rouges les antigènes A et B et n’a pas d’anticorps anti-A ni anti-B"], correct: 3 , explanation:"Les individus AB ont les antigènes A et B et aucun anticorps, ce qui leur permet de recevoir tous les types de sang." },
        


        { subject: "Géologie", question: "  Quelles sont les différences principales entre planètes gazeuses et telluriques ?", answers: ["Gazeuses → solides ; Telluriques → gazeuses", "Gazeuses → très denses ; Telluriques → peu denses", "Gazeuses → constituées surtout de gaz ; Telluriques → solides et rocheuses","Gazeuses → petites ; Telluriques → énormes"], correct: 3 , explanation:" Les planètes telluriques (Terre, Mars, Vénus, Mercure) sont rocheuses et denses, tandis que les planètes gazeuses (Jupiter, Saturne, Uranus, Neptune) sont composées de gaz." },
        { subject: "Géologie", question: "  Pourquoi dit-on que la Terre est une planète tellurique ?", answers: ["Parce qu’elle a un océan", "Parce qu’elle est rocheuse et solide", " Parce qu’elle a des satellites", "Parce qu’elle tourne autour du Soleil"], correct: 2 , explanation:" La Terre a une surface solide composée principalement de silicates et de fer, caractéristique des planètes telluriques." },
        { subject: "Géologie", question: "  Deux planètes telluriques du système solaire.", answers: ["Jupiter et Saturne", "Mars et Vénus", "Uranus et Neptune", "Mercure et Jupiter"], correct: 2 , explanation:" Les planètes telluriques sont Mercure, Vénus, Terre et Mars." },
        { subject: "Géologie", question: "  Quelle est l’origine de l’atmosphère terrestre ?", answers: ["Activité humaine", "Impacts météoritiques", "Décomposition des roches sédimentaires", "Volcanisme intense"], correct: 3 , explanation:"Les gaz volcaniques libérés par le manteau ont constitué l’atmosphère primitive. " },
        { subject: "Géologie", question: "  Comment est formé le premier océan ?", answers: ["Par fusion de la croûte terrestre", " Par condensation de la vapeur d’eau atmosphérique", "Par accumulation de glace", "Par précipitation de CO2"], correct:  2, explanation:"  La vapeur d’eau atmosphérique s’est condensée pour former les premiers océans." },
        { subject: "Géologie", question: "  Quels gaz étaient présents dans l’atmosphère primitive et lequel n’y était pas ?", answers: ["Présents : H2O, CO2, N2 ; Absents : O2", " Présents : O2 ; Absents : CO2", "Présents : H2 ; Absents : N2", " Présents : O2, N2 ; Absents : CO2"], correct: 1 , explanation:" L’atmosphère primitive contenait H2O, CO2 et N2, mais pas de dioxygène." },
        { subject: "Géologie", question: "  Les océans sont des réservoirs de carbone car ils absorbent le CO2 atmosphérique.", answers: ["Vrai", "Faux", ], correct: 1 , explanation:" Le CO2 atmosphérique est en partie dissous dans les océans et participe à la formation de carbonates." },
        { subject: "Géologie", question: "  Pourquoi les variations de densité de l’eau marine sont importantes pour la circulation océanique ?", answers: ["Elles provoquent des séismes", "Elles créent des courants océaniques", "Elles modifient la couleur de l’eau", " Elles produisent des vagues"], correct: 2 , explanation:"Les différences de densité entraînent des mouvements verticaux et horizontaux, essentiels pour la circulation océanique." },
        { subject: "Géologie", question: "  Pourquoi les comètes ont-elles une durée de vie limitée ?", answers: ["Elles fusionnent entre elles", "Elles tombent toujours sur Terre", "Elles sont détruites par les collisions avec les planètes", "Leur matière s’évapore lorsqu’elles s’approchent du Soleil"], correct: 3 , explanation:"La chaleur du Soleil provoque l’évaporation de la glace et des gaz, réduisant progressivement leur masse. " },
        { subject: "Géologie", question: "  Qu’est-ce qu’un astéroïde ?", answers: ["Une étoile éteinte", "Un petit corps rocheux orbitant autour du Soleil", "Une planète naine", "Un satellite naturel"], correct:  2, explanation:" Les astéroïdes sont des corps rocheux ou métalliques, souvent situés dans la ceinture d’astéroïdes entre Mars et Jupiter." },

        // Thème I : Glycémie
        { subject: "Biologie", question: "Quel nutriment résulte de la digestion des glucides ?", answers: ["Lipides", "Protéines", "Glucose", "Acides aminés"], correct: 2, explanation: "Les glucides sont digérés en glucose, qui est la principale source d’énergie pour les cellules." },
        { subject: "Biologie", question: "Sous quelle forme le glucose est-il mis en réserve dans l’organisme ?", answers: ["Glucides simples", "Glycogène", "Acides gras", "Protéines"], correct: 1, explanation: "Le glucose excédentaire est stocké sous forme de glycogène dans le foie et les muscles." },
        { subject: "Biologie", question: "Où se stocke le surplus de glucose ?", answers: ["Foie et muscles", "Estomac et intestin", "Pancréas uniquement", "Poumons"], correct: 0, explanation: "Le glycogène est principalement stocké dans le foie et les muscles pour fournir de l’énergie en cas de besoin." },
        { subject: "Biologie", question: "Quelle hormone participe à la mise en réserve du glucose et quelle est son origine ?", answers: ["Glucagon – Pancréas", "Insuline – Pancréas", "Adrénaline – Glandes surrénales", "Cortisol – Glandes surrénales"], correct: 1, explanation: "L’insuline, sécrétée par les cellules bêta du pancréas, favorise le stockage du glucose sous forme de glycogène." },

        // Thème II : ADN et ARN
        { subject: "Biologie", question: "Comment s’appelle le transfert du message codé de l’ADN du noyau vers le cytoplasme ?", answers: ["Traduction", "Transcription", "Réplication", "Mutation"], correct: 1, explanation: "La transcription est le processus par lequel l’ARN messager copie l’information de l’ADN pour la transporter vers le cytoplasme." },
        { subject: "Biologie", question: "Quelle structure transporte l’information de l’ADN vers le cytoplasme ?", answers: ["Ribosome", "ARNm", "Mitochondrie", "Membrane plasmique"], correct: 1, explanation: "L’ARN messager (ARNm) transporte le message génétique du noyau vers les ribosomes pour la synthèse des protéines." },
        { subject: "Biologie", question: "En quoi consiste la traduction ?", answers: ["Copie de l’ADN", "Conversion de l’ARN en protéines", "Synthèse d’ARN", "Division cellulaire"], correct: 1, explanation: "La traduction est le processus où le ribosome utilise l’ARNm pour assembler les acides aminés et former une protéine." },
        { subject: "Biologie", question: "Quels autres acteurs interviennent dans la traduction ?", answers: ["ARNt et ribosomes", "ADN et mitochondries", "Lipides et enzymes digestives", "Glucides et vitamines"], correct: 0, explanation: "Les ribosomes réalisent la synthèse, et l’ARN de transfert (ARNt) apporte les acides aminés correspondants aux codons de l’ARNm." },

        // Thème I : Enveloppes fluides animées par l’énergie solaire
        { subject: "Géologie", question: "Quelle est la différence entre atmosphère et hydrosphère ?", answers: ["Atmosphère → eau liquide ; Hydrosphère → air", "Atmosphère → air ; Hydrosphère → eau liquide", "Atmosphère → roches ; Hydrosphère → air", "Atmosphère → glace ; Hydrosphère → vapeur"], correct: 1, explanation: "L’atmosphère est la couche de gaz entourant la Terre, tandis que l’hydrosphère comprend toutes les eaux liquides et les glaces." },
        { subject: "Géologie", question: "En quoi l’atmosphère primitive se différencie-t-elle de l’actuelle ?", answers: ["Primitive riche en O2", "Primitive pauvre en O2 et riche en CO2 et H2O", "Même composition que l’actuelle", "Contient uniquement du N2"], correct: 1, explanation: "L’atmosphère primitive contenait principalement CO2, H2O et N2, sans dioxygène libre." },
        { subject: "Géologie", question: "Quelle est l’origine des mouvements des masses atmosphériques et océaniques ?", answers: ["Rotation terrestre et inégale répartition de l’énergie solaire", "Tectonique des plaques", "Mouvements volcaniques", "Gravité lunaire"], correct: 0, explanation: "Les différences de température dues au rayonnement solaire et la rotation terrestre génèrent vents et courants océaniques." },

        // Thème II : Modèle sismique
        { subject: "Géologie", question: "Qu’est-ce qu’une onde sismique ?", answers: ["Un mouvement des plaques tectoniques", "Une vibration libérée lors d’un séisme", "Une montagne formée par un volcan", "Une tempête océanique"], correct: 1, explanation: "Une onde sismique est l’énergie libérée lors de la rupture des roches, se propageant sous forme de vibrations." },
        { subject: "Géologie", question: "Quelle est la différence entre foyer et épicentre d’un séisme ?", answers: ["Foyer → surface ; Épicentre → profondeur", "Foyer → point de rupture ; Épicentre → point à la verticale du foyer à la surface", "Même chose", "Foyer → magma ; Épicentre → lave"], correct: 1, explanation: "Le foyer est l’origine profonde du séisme, l’épicentre est le point correspondant à la surface." },

        // Deuxième Partie – Généralités
        { subject: "Géologie", question: "Différence entre cratère d’impact et cratère volcanique ?", answers: ["Impact → météorite ; Volcanique → magma", "Impact → lave ; Volcanique → vent", "Impact → glace ; Volcanique → roche", "Idem"], correct: 0, explanation: "Les cratères d’impact sont formés par la collision d’un astéroïde, les cratères volcaniques par éruption de magma." },
        { subject: "Géologie", question: "Pourquoi les courants marins de surface corrigent-ils les inégalités thermiques ?", answers: ["Transportent la chaleur d’une région à l’autre", "Augmentent la salinité", "Produisent des vagues", "Rafraîchissent l’atmosphère uniquement"], correct: 0, explanation: "Les courants marins déplacent de l’eau chaude et froide, régulant la température globale de la planète." },
        { subject: "Géologie", question: "Définir gravitation.", answers: ["Force qui attire les objets vers le centre de la Terre", "Mouvement des océans", "Rotation terrestre", "Pression atmosphérique"], correct: 0, explanation: "La gravitation est la force d’attraction entre les masses, responsable du poids des objets et de la cohésion des planètes." },

        // Thème I : Vitamines
        { subject: "Biologie", question: "Quelle avitaminose provoque le scorbut ?", answers: ["Carence en vitamine A", "Carence en vitamine C", "Carence en vitamine D", "Carence en vitamine E"], correct: 1, explanation: "Le scorbut est causé par un déficit en vitamine C, entraînant fatigue, gencives qui saignent et troubles de cicatrisation." },
        { subject: "Biologie", question: "Quelle avitaminose provoque la xérophtalmie ?", answers: ["Carence en vitamine A", "Carence en vitamine C", "Carence en vitamine D", "Carence en vitamine E"], correct: 0, explanation: "La xérophtalmie est due à un manque de vitamine A, provoquant sécheresse oculaire et cécité nocturne." },
        { subject: "Biologie", question: "Donner deux sources alimentaires de la vitamine D.", answers: ["Lait et poisson gras", "Viande et eau", "Riz et pain", "Fruits et légumes"], correct: 0, explanation: "La vitamine D se trouve dans les poissons gras, le lait enrichi et l’exposition solaire favorise sa synthèse." },
        { subject: "Biologie", question: "Donner deux sources alimentaires de la vitamine E.", answers: ["Huiles végétales et noix", "Lait et poisson", "Riz et viande", "Oeufs et eau"], correct: 0, explanation: "Les huiles végétales, graines et noix sont riches en vitamine E, un antioxydant." },

        // Thème II : Généralités (Biologie)
        { subject: "Biologie", question: "Que sont les allèles ?", answers: ["Les différentes formes d’un gène", "Une cellule spécialisée", "Un type de chromosome", "Un organite"], correct: 0, explanation: "Les allèles sont les variantes possibles d’un même gène, déterminant différentes expressions d’un caractère." },
        { subject: "Biologie", question: "Quel est le caryotype d’une cellule humaine issue de la spermatogenèse ?", answers: ["46 chromosomes", "23 chromosomes", "22 chromosomes", "44 chromosomes"], correct: 1, explanation: "Les gamètes (spermatozoïdes) sont haploïdes et contiennent 23 chromosomes." },
        { subject: "Biologie", question: "Quelles hormones régulent la calcémie ?", answers: ["Parathormone et calcitonine", "Insuline et glucagon", "Adrénaline et cortisol", "Thyroxine et oestrogènes"], correct: 0, explanation: "La parathormone augmente le calcium sanguin, la calcitonine le diminue, maintenant l’équilibre calcique." },

        // Deuxième Partie – Daltonisme
        { subject: "Biologie", question: "Daltonisme – croisement homme daltonien × femme vectrice : quelle proportion de fils daltoniens ?", answers: ["0 %", "25 %", "50 %", "100 %"], correct: 2, explanation: "Le gène est lié à l’X : fils ont 50 % de chance d’hériter de l’allèle défectueux." },

        // Thème III : Pancréas
        { subject: "Biologie", question: "Le pancréas est une glande amphicrine car il a des fonctions exocrines et endocrines.", answers: ["Vrai", "Faux"], correct: 0, explanation: "Il produit des enzymes digestives (exocrine) et des hormones comme l’insuline et le glucagon (endocrine)." },
        { subject: "Biologie", question: "Quelles sont les sécrétions du pancréas et leurs cellules productrices ?", answers: ["Enzymes digestives → acini ; Hormones → îlots de Langerhans", "Enzymes → îlots ; Hormones → acini", "Glucides → acini ; Protéines → îlots", "Lipides → acini ; Glucides → îlots"], correct: 0, explanation: "Les acini sécrètent les enzymes digestives, les îlots de Langerhans sécrètent insuline et glucagon." },
        { subject: "Biologie", question: "Comment le pancréas régule-t-il la glycémie ?", answers: ["En stockant le glucose", "Par sécrétion d’insuline et de glucagon", "Par digestion des lipides", "Par filtration sanguine"], correct: 1, explanation: "L’insuline diminue la glycémie en favorisant le stockage, le glucagon l’augmente en libérant du glucose." },

        // Thème I : Changement climatique (Géologie)
        { subject: "Géologie", question: "Définition de l’effet de serre ?", answers: ["Accumulation de CO2 et réchauffement de la surface terrestre", "Chute de neige intense", "Rafraîchissement de l’atmosphère", "Formation des nuages uniquement"], correct: 0, explanation: "Les gaz à effet de serre retiennent la chaleur émise par la Terre, réchauffant la surface." },
        { subject: "Géologie", question: "Définition des pluies acides ?", answers: ["Pluies normales", "Pluies chargées en gaz acides (SO2, NOx)", "Pluies contenant du sel marin", "Pluies artificielles uniquement"], correct: 1, explanation: "Les pluies acides sont causées par les oxydes de soufre et d’azote, responsables de la corrosion et de la dégradation des sols et végétaux." },

        // Thème II : Les minerais (Géologie)
        { subject: "Géologie", question: "Minerai vs Minéral : quelle différence ?", answers: ["Minerai → exploitable ; Minéral → substance naturelle", "Minerai → eau ; Minéral → air", "Minerai → métal ; Minéral → végétal", "Minerai = minéral"], correct: 0, explanation: "Un minerai contient un métal exploitable, un minéral est une substance naturelle inorganique." },
        { subject: "Géologie", question: "Quels sont les minerais métalliques d’Haïti ?", answers: ["Or, cuivre, fer", "Sel, sable, argile", "Charbon, pétrole, gaz", "Bois, eau, calcaire"], correct: 0, explanation: "Haïti possède des gisements d’or, de cuivre et de fer exploitables." },
        { subject: "Géologie", question: "Quelles sont les étapes de la prospection minière ?", answers: ["Observation → Échantillonnage → Analyse → Exploitation", "Semis → Récolte → Analyse", "Forage → Construction → Commercialisation", "Extraction → Vente → Marketing"], correct: 0, explanation: "La prospection commence par observation, suivie d’échantillonnage et analyses avant exploitation." },

        // Deuxième Partie – Généralités (Géologie)
        { subject: "Géologie", question: "Exemple de macrofossile et microfossile ?", answers: ["Macro → ammonite ; Micro → foraminifères", "Macro → bactéries ; Micro → poisson", "Macro → pierre ; Micro → sable", "Macro → feuille ; Micro → arbre"], correct: 0, explanation: "Les macrofossiles sont visibles à l’œil nu, les microfossiles nécessitent un microscope." },
        { subject: "Géologie", question: "Critères d’appartenance à la lignée humaine ?", answers: ["Bipédie, capacité crânienne élevée, usage d’outils", "Quadrupédie, petites mains, poils abondants", "Queue longue, griffes", "Ailes, plumes"], correct: 0, explanation: "Les humains se distinguent par la marche bipède, un cerveau volumineux et la fabrication d’outils." },
        { subject: "Géologie", question: "Comment les météorites ont-elles permis de comprendre la structure interne de la Terre ?", answers: ["Elles contiennent des minéraux similaires au manteau et au noyau", "Elles modifient le climat", "Elles produisent des séismes", "Elles génèrent des volcans"], correct: 0, explanation: "L’étude de la composition des météorites donne des indices sur les éléments présents dans le manteau et le noyau terrestre." },

        { subject: "Géologie", question: "Groupes d’espèces animales disparues à la fin du Crétacé", answers: ["Dinosaures et ammonites", "Mammifères", "Oiseaux", "Poissons"], correct: 0, explanation: "La fin du Crétacé est marquée par l’extinction des dinosaures et ammonites." },
        { subject: "Géologie", question: "Définition de l’indice en géologie", answers: ["Minéral indicateur d’une couche ou période", "Masse totale d’un minerai", "Température d’éruption", "Type de roche"], correct: 0, explanation: "L’indice permet de dater ou caractériser une formation géologique." },
        { subject: "Géologie", question: "Définition de tonnage", answers: ["Quantité de minerai exploitable", "Nombre de fossiles", "Profondeur d’une roche", "Surface d’un volcan"], correct: 0, explanation: "Le tonnage indique la masse totale d’un minerai dans un gisement." },
        { subject: "Géologie", question: "Méthodes de datation en géologie", answers: ["Radiométrique et relative (stratigraphie)", "Seul radiocarbone", "Observation visuelle", "Magnétisme"], correct: 0, explanation: "La datation relative compare les couches, la radiométrique mesure l’âge absolu via isotopes." },
        { subject: "Géologie", question: "Origine de l’atmosphère terrestre", answers: ["Volcanisme intense libérant CO2, H2O, N2", "Collision météoritique uniquement", "Photosynthèse humaine", "Refroidissement de l’espace"], correct: 0, explanation: "L’atmosphère primitive provient de gaz volcaniques, sans O2 libre initialement." },
        { subject: "Géologie", question: "Structure interne du globe terrestre", answers: ["Croûte, manteau, noyau externe et noyau interne", "Croûte uniquement", "Manteau uniquement", "Atmosphère et hydrosphère"], correct: 0, explanation: "La Terre se compose de ces quatre couches distinctes avec propriétés physiques différentes." },

        // Microbiologie (Biologie)
        { subject: "Biologie", question: "Définition d’un agent pathogène ?", answers: ["Organisme capable de provoquer une maladie", "Organisme inoffensif", "Virus uniquement", "Bactéries uniquement"], correct: 0, explanation: "Un agent pathogène est tout microorganisme pouvant causer une infection." },
        { subject: "Biologie", question: "Définir hôte ?", answers: ["Organisme qui héberge un agent pathogène", "Organisme immunisé uniquement", "Virus seulement", "Bactérie seulement"], correct: 0, explanation: "L’hôte est l’organisme dans lequel un agent pathogène vit et se multiplie." },
        { subject: "Biologie", question: "Nommer deux bactéries de forme arrondie et deux de forme allongée", answers: ["Coco : Streptococcus, Staphylococcus ; Bacille : Escherichia coli, Bacillus subtilis", "Coco : E. coli, Bacillus ; Bacille : Streptococcus, Staphylococcus", "Coco : Salmonella, Clostridium ; Bacille : Lactobacillus, Vibrio", "Coco : Vibrio, Bacillus ; Bacille : Salmonella, Clostridium"], correct: 0, explanation: "Les cocci sont sphériques, les bacilles sont allongés." },
        { subject: "Biologie", question: "Quelle condition est obligatoire pour la multiplication des virus dans les plantes ?", answers: ["Présence d’une cellule hôte vivante", "Eau uniquement", "Soleil", "Minéraux du sol"], correct: 0, explanation: "Les virus sont parasites intracellulaires obligatoires, nécessitant une cellule vivante pour se répliquer." },
        { subject: "Biologie", question: "Quel acide nucléique contient un virus ?", answers: ["ADN ou ARN", "Protéine uniquement", "Lipide", "Glucide"], correct: 0, explanation: "Les virus contiennent soit de l’ADN soit de l’ARN comme matériel génétique." },
        { subject: "Biologie", question: "Qu’est-ce qu’un rétrovirus ? Exemple.", answers: ["Virus utilisant la transcriptase inverse ; Exemple : VIH", "Virus bactérien ; Exemple : E. coli", "Virus végétal ; Exemple : Tabac", "Virus inactif ; Exemple : Poliovirus"], correct: 0, explanation: "Les rétrovirus convertissent leur ARN en ADN via la transcriptase inverse pour s’intégrer dans l’ADN de l’hôte." },

        // Généralités Biologie
        { subject: "Biologie", question: "Qu’est-ce qu’un allèle ?", answers: ["Différentes formes d’un même gène", "Chromosome entier", "Cellule spécialisée", "Organite"], correct: 0, explanation: "Les allèles déterminent différentes versions d’un caractère génétique." },
        { subject: "Biologie", question: "Pathologie résultant de la déformation des globules rouges ?", answers: ["Drépanocytose", "Anémie ferriprive", "Diabète", "Cholestérolémie"], correct: 0, explanation: "La drépanocytose est causée par des globules rouges en forme de faucille." },
        { subject: "Biologie", question: "Nommer les acteurs de la traduction", answers: ["ARNm, ARNt, ribosomes", "ADN, mitochondrie", "Lipides, enzymes", "Glucides, vitamines"], correct: 0, explanation: "La traduction utilise l’ARNm comme modèle, l’ARNt pour transporter les acides aminés et les ribosomes pour assembler la protéine." },

        // Daltonisme (Biologie)
        { subject: "Biologie", question: "Comment se caractérise le daltonisme ?", answers: ["Déficit dans la perception des couleurs", "Malformation de la rétine", "Vision floue uniquement", "Cécité totale"], correct: 0, explanation: "Le daltonisme est dû à un défaut d’un ou plusieurs types de cônes dans la rétine, affectant la perception des couleurs." },
        { subject: "Biologie", question: "Mode de transmission du daltonisme", answers: ["Gène situé sur le chromosome X", "Chromosome Y", "Chromosome 21", "Transmission autosomique dominante"], correct: 0, explanation: "Le daltonisme est une maladie liée à l’X, donc les hommes sont plus fréquemment atteints." },
        { subject: "Biologie", question: "Pourquoi un père daltonien ne transmet jamais cette tare à ses fils ?", answers: ["Car le fils reçoit le chromosome Y du père", "Car le fils reçoit le chromosome X du père", "Car la mère est toujours saine", "Car c’est une maladie dominante"], correct: 0, explanation: "Le fils reçoit le chromosome Y du père, donc l’allèle défectueux lié à l’X n’est pas transmis." },

        { subject: "Chimie", question: "Quel est le symbole chimique de l'or ?", answers: ["Ag", "Au", "Fe"], correct: 1, explanation: "Le symbole 'Au' pour l'or vient de son nom latin 'Aurum'. 'Ag' est le symbole de l'argent (Argentum) et 'Fe' est celui du fer (Ferrum)." },
        { subject: "Philosophie", question: "Qui a écrit 'Le Contrat Social' ?", answers: ["Voltaire", "Rousseau", "Montesquieu"], correct: 1 },
        { subject: "Physique", question: "Quelle est l'unité de mesure de la tension électrique ?", answers: ["Ampère", "Watt", "Volt"], correct: 2 },
        { subject: "Maths", question: "Calculez l'aire d'un cercle de rayon 5cm (π ≈ 3.14).", answers: ["78.5 cm²", "31.4 cm²", "15.7 cm²"], correct: 0 }
    ],
    LLA: [
        { subject: "Art", question: "Qui a écrit 'L'Étranger' ?", answers: ["Victor Hugo", "Albert Camus", "Marcel Proust"], correct: 1 },
        { subject: "Philosophie", question: "Quel mouvement littéraire est associé à Charles Baudelaire ?", answers: ["Le Romantisme", "Le Surréalisme", "Le Symbolisme"], correct: 2 },
        { subject: "Anglais", question: "Which of these is a synonym for 'happy'?", answers: ["Sad", "Joyful", "Angry"], correct: 1 },
        { subject: "Espagnol", question: "Traduce 'libro' al francés.", answers: ["Livre", "Table", "Chaise"], correct: 0 },
        { subject: "Créole", question: "Ki powèt ayisyen ki ekri 'Pèlen Tèt' ?", answers: ["Félix Morisseau-Leroy", "Frankétienne", "Georges Castera"], correct: 1 },
        { subject: "Musique", question: "Combien de cordes une guitare classique a-t-elle généralement ?", answers: ["4", "6", "8"], correct: 1 },
        { subject: "Sciences Sociales", question: "Quel est le plus grand océan du monde ?", answers: ["Atlantique", "Indien", "Pacifique"], correct: 2 }
    ],
    SMP: [
        { subject: "Maths", question: "Combien de côtés a un hexagone ?", answers: ["5", "6", "7"], correct: 1 },
        { subject: "Physique", question: "Quelle loi de Newton stipule que 'toute action entraîne une réaction égale et opposée' ?", answers: ["Première loi", "Deuxième loi", "Troisième loi"], correct: 2 },
        { subject: "Chimie", question: "Quelle est la formule chimique de l'eau ?", answers: ["CO2", "H2O", "O2"], correct: 1 },
        { subject: "Anglais", question: "What is the capital of the UK?", answers: ["Paris", "London", "Berlin"], correct: 1 },
        { subject: "Biologie", question: "Quel organite est la 'centrale énergétique' de la cellule ?", answers: ["Noyau", "Mitochondrie", "Ribosome"], correct: 1 },
        { subject: "Philosophie", question: "Quel philosophe grec était le maître d'Alexandre le Grand ?", answers: ["Platon", "Socrate", "Aristote"], correct: 2 }
    ]
};